### ISSUE TITLE
能不能发个Chrome 下载地址

### ISSUE THREAD

**Issue by coolf** [LeiShi1313/scf-headless-chrome#2]
chromedriver/headless-chromium-tencent (cb84abf): Smudge error: Error downloading chromedriver/headless-chromium-tencent (cb84abf7e7f5b2bdebd5c26adba2d5e6ccd66916798a2cb5675fc73c3aaaa1ad): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by LeiShi1313** [comment]
放到release里了，应该不会被限制了
